version: 2
# Project information
project:
  name: Awesome-GNN-based-drug-discovery
  version: latest
  language: python

# Build configuration
build:
  os: macos
  image: latest
  configuration: .readthedocs.yml

# Documentation configuration
docs:
  version: latest
  format: markdown
  source_dir: .
  build_dir: _build

# Define submodules if your repository includes any
submodules:
  include: all
  recursive: true

